### ISSUE TITLE
Issues with linting Custom Resource Definition

### ISSUE THREAD

**Issue by alisondy** [garethr/kubernetes-json-schema#10]
I notice that the custom resource definition liniting files are broken up, but the latest version of kubeval doesn't respect this

``` Problem loading schema from the network at https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/v1.9.0-standalone/customresourcedefinition.json: Could not read schema from HTTP, response status is 404 Not Found```

![screenshot from 2018-08-14 17-20-52](https://user-images.githubusercontent.com/19580905/44073127-73c51528-9fe6-11e8-9250-2bbfaccd4d26.png)

Does some work need to be done in kubeval to respect this or does the json schema need to be updated?

**Comment by ellieayla** [comment]
Same as #5

**Comment by alisondy** [comment]
closing as duplicate 👍
