### ISSUE TITLE
1.13.x Schemas

### ISSUE THREAD

**Issue by rhockenbury** [garethr/kubernetes-json-schema#17]
Please consider adding schemas for kubernetes 1.13

**Comment by grzesuav** [comment]
https://github.com/garethr/kubernetes-json-schema/pull/15

**Comment by garethr** [comment]
Just catching up on lots of maintenance. I'e pushed a full set of 1.13.x schemas today too.

**Comment by rhockenbury** [comment]
Thank you!!
