### ISSUE TITLE
v1.12.8 schemas are missing

### ISSUE THREAD

**Issue by ghost** [garethr/kubernetes-json-schema#23]
kubernetes v1.12.8 is what's shipped by kops v1.12.1, so it'd be nice to use that exact version. I'll resort to using v1.12.6 schemas for now.

**Comment by garethr** [comment]
Thanks for the heads up. I've moved the canonical location for these schemas to a new repo, and I"ve just published the missing schemas. https://github.com/instrumenta/kubernetes-json-schema/commit/3c9bf344e7ed09602e1df5fe86e6880f8236d370

I'll be deprecating this repo soon with a handy pointer to the new one.

Thanks for letting me know.
